app:
  name: CurrencyExchangeApp
  port: 8000

database:
  dsn: "thomas:huan1122@tcp(127.0.0.1:3306)/currency_exchange?charset=utf8mb4&parseTime=True&loc=Local"
  maxIdleConns: 11
  maxOpenConns: 114
  